language: python
services:
- docker
python:
- '3.6'
before_script:
- export LOCAL_POSTGRES_PORT_RANGE=5432
- docker-compose build
script:
- docker-compose run --rm web bash -c "python postgres_ready.py && ./manage.py test"
after_success:
- docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
- docker tag web registry.heroku.com/grindhouse/web
- docker push registry.heroku.com/grindhouse/web
notifications:
  email: true
cache:
  pip: true
env:
  global:
    secure: jkSJ++kepKkyao9/ym9/9oJ99/izZuvj6Jw+xaK6Z9B7MPI+zmoSP2O+KRgA4CUeJLEZpBAmfk3rrxk0jt7dp3mHvLMWHul8eq60AoEWgoHRZSYb0zyLKXnSPPxm06Ss/LUyZnDFsJ3lI3Uh4FjHKhUF639rNvcaTQkYCKzNREjPnWJL8mIcMBgVibXW9hKMc/4SZdkb5h3T911fPaaGHMbc0aEA24v7S4aQ4JlV9XsZtQSORcySJwgQcF0w2c3DiZ1JSokySc7+Rg+GOrtEexNdMC8MuVfiATyxWzZ8HVDN5GddPAVjSdEPoYVDnNegQH7oPgZoviR/bzJCP+gmg7rOChVXDr/W+0DXFERzBHADAt2YHBLVJJSN2XWgzvif/BX6wPvT9GlrXqf6hamVdVaAdyNxZLapfS6JgWcFxiJB30Qj7Q+h27iSzPE/DTIYUYKpE49D+n1nFoBI0UhONghbyJenRG4/FYBuMGPsdsQQk26mHDqgxUH8SILnaByAlu8YmtqoflDiO1RLr8Sh1rKcsYtYLbP8QWN+OQHbh73aFdVInPMPNX/wlXDenudd/eFj1jzi0r2yZ14VfG1RARk0iqqhz1tv7HDbDDTgE1QP/bQCzSaEy6bJL7zYFBGIRbaWFs81j2Iim50E96MYuUd6CEn3wd5Xnv6u1y36tW8=
